import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


// Definitions: 
// Dictionary(dictionary) - array of strings which represents words that we want to have some animation
// Text string(psuedoDynamicString) - our text source on which we will apply dynamic animations


// in this example dictionary and text string are constants.
// I would suggest to create separate component and provide both text string and dictionary as props
const dictionary  = ['Hello', 'Bonjour', 'Привет', 'Guten Tag', 'Привит','Dzień Dobry']
const pesudoDynamicString = 'To greet someone we ususally say Hello, French people say Bonjour, Russians Привет, Germans Guten Tag, Ukrainians Привит, and Poles say Dzień Dobry'

export default function Home() {
  // here we create regex for words that we are looking for in text string
  const regExp = new RegExp(dictionary.join('|'), 'gi')
  // then we create array of jsx templates which can be rendered by virtual dom
  // we mark found words so we can animate them later
  // after we have array of plain text and marked words we apply animation
  const jsxArray = pesudoDynamicString.replace(regExp, (word) => `&#0;<animate>${word}&#0;`)
    .split('&#0;')
    .map(string => {
      if(string.includes('<animate>')) {
        const text = string.replace('<animate>', '')
        return <span className={styles.rotate}>{text}</span>
      } else {
        return string;
      }
    })
  console.log(jsxArray)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* put generated template in place */}
      <p>{jsxArray}</p>
    </div>
  )
}
